#Data Preprocessing

In [31]:
import pandas as pd
import numpy as np


In [32]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [33]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [34]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target


In [35]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [36]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [37]:
y

array([5, 5, 5, ..., 6, 5, 6])

#Splitting of data into test and train 

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [40]:
y_train

array([5, 8, 5, ..., 5, 5, 5])

In [41]:
y_test

array([6, 6, 5, 5, 7, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5,
       8, 5, 6, 6, 5, 5, 5, 6, 6, 5, 7, 5, 5, 6, 6, 5, 6, 6, 6, 7, 6, 8,
       6, 6, 7, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 6, 3, 6, 7, 7, 6,
       5, 7, 6, 5, 6, 5, 5, 7, 4, 5, 6, 4, 6, 4, 6, 5, 6, 5, 5, 5, 6, 6,
       5, 6, 5, 7, 6, 5, 5, 6, 5, 4, 5, 4, 6, 7, 5, 5, 7, 8, 4, 7, 7, 6,
       5, 7, 5, 6, 7, 6, 6, 6, 6, 7, 6, 6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 6,
       7, 6, 5, 7, 6, 6, 5, 5, 6, 4, 5, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6,
       6, 6, 5, 5, 6, 5, 5, 7, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6,
       6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 7, 7, 5, 5, 6, 3, 6, 7, 4, 5, 6, 7,
       5, 4, 5, 5, 5, 6, 6, 7, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 7, 7, 5, 6,
       6, 5, 6, 7, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 4, 6, 5, 6, 7, 5,
       7, 6, 5, 5, 5, 6, 5, 7, 6, 5, 5, 6, 5, 6, 4, 6, 7, 6, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 5, 8, 7, 4, 5, 5, 6, 5, 6, 6, 7, 5, 5, 6, 5, 5, 5,
       7, 6, 7, 6, 5, 7, 6, 5, 4, 6, 6, 5, 6, 5, 6,

#Standardization

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
ptrain = y_train.reshape(len(y_train), 1)
ptest = y_test.reshape(len(y_test), 1)

In [44]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [45]:
xp_train = x_sc.fit_transform(x_train)
yp_train = y_sc.fit_transform(ptrain)

In [46]:
xp_test = x_sc.transform(x_test)
yp_test = y_sc.transform(ptest)

In [47]:
len(xp_train)

1279

In [48]:
xp_train

array([[ 9.56173919e-01,  2.93599359e-01, -2.70795150e-01, ...,
        -1.17820512e+00, -6.43631854e-01, -8.62047024e-01],
       [ 1.51755098e-01, -5.89053393e-01,  6.07602426e-01, ...,
         2.81542830e-01,  1.81163965e-01,  1.23096621e+00],
       [ 1.51755098e-01, -2.02892814e-01,  9.08979693e-02, ...,
        -2.50524872e+00,  7.78106830e+00, -5.76636129e-01],
       ...,
       [-7.67580698e-01,  4.03930953e-01,  1.42568415e-01, ...,
        -5.02180688e-02,  3.00903534e+00, -1.96088269e-01],
       [-1.28470708e+00,  9.83171822e-01, -8.90840499e-01, ...,
         1.94034732e+00,  4.42200372e-03, -1.96088269e-01],
       [-9.97414647e-01,  1.94857327e+00, -1.20086317e+00, ...,
         1.47588206e+00, -5.84717867e-01, -4.81499164e-01]])

In [49]:
len(xp_test)

320

In [50]:
xp_test

array([[-0.42282977,  1.03833762, -1.40754496, ...,  1.14412117,
        -0.05449198,  0.94555531],
       [ 1.01363241, -1.41654035,  1.38265911, ..., -0.9127964 ,
        -0.76145983,  1.99206193],
       [-0.82503919, -0.03739542, -0.11578381, ...,  1.01141681,
        -0.93820179,  0.56500745],
       ...,
       [-0.99741465,  0.29359936, -1.40754496, ...,  1.87399514,
         0.12224998,  0.94555531],
       [-0.93995616, -0.36839021, -0.16745426, ...,  0.54695155,
        -0.34906192,  0.18445959],
       [-1.85929196, -0.31322441, -1.30420406, ...,  3.93091271,
        -0.23123394,  2.27747282]])

In [51]:
yp_train

array([[-0.78896945],
       [ 2.93461699],
       [-0.78896945],
       ...,
       [-0.78896945],
       [-0.78896945],
       [-0.78896945]])

#Train on different algorithms

In [52]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [53]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [54]:
x_pol = PolynomialFeatures(degree=5)
x_pol = x_pol.fit_transform(xp_train)

In [55]:
temp = PolynomialFeatures(degree=5)
temp = temp.fit_transform(xp_test)

In [56]:
r_reg.fit(xp_train, yp_train)
l_reg.fit(xp_train, yp_train)
d_reg.fit(xp_train, yp_train)
s_reg.fit(xp_train, yp_train)
p_reg.fit(x_pol, yp_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
r_pred = r_reg.predict(xp_test)
l_pred = l_reg.predict(xp_test)
d_pred = d_reg.predict(xp_test)
s_pred = s_reg.predict(xp_test)
p_pred = p_reg.predict(temp)

#Result

In [58]:

from sklearn.metrics import r2_score

In [59]:
r = r2_score(yp_test, r_pred)
l = r2_score(yp_test, l_pred)
d = r2_score(yp_test, d_pred)
s = r2_score(yp_test, s_pred)
p = r2_score(yp_test, p_pred)

In [60]:
print(r, l, d, s, p)

0.5015447039396083 0.33747468687425575 0.15074309978768563 0.44045828905471185 -1399.023996975208


#Conclusion

###We have solved it using regression techique



*   As we have observed RandomForest is giving more efficiency 
    than any other algorithmic techniques
    ,so we can conclude that RandomForest is the best algorithmic       technique for this data set.
